server:
  port: 8084

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

info:
  app:
    name: catalog-service
    description: Catalog Service
    version: 1.0.0
