server:
  port: 8080
  
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: http://localhost:8082/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movie/**
        - id: libraryRoute #Identificando la ruta del service de producto
          uri: http://localhost:8084/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/libraries/**
