server:
  port: 8082

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:parcialBackend;DB_CLOSE_DELAY=-1;
    username: sa
    password: 
  sql:
    init:
      data-locations: classpath:movie.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

info:
  app:
    name: movie-service
    description: Movie Service
    version: 1.0.0
